server:
  port: 10021
spring:
  application:
    name: xred-service-discovery-multi-provider
  autoconfigure:
    exclude: org.springframework.cloud.client.serviceregistry.ServiceRegistryAutoConfiguration,org.springframework.cloud.client.serviceregistry.AutoServiceRegistrationAutoConfiguration
  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        instance-id: ${spring.application.name}-02
        service-name: ${spring.application.name}
        port: ${server.port}
        prefer-ip-address: true
        ip-address: ${spring.cloud.client.ip-address}
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10013/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
