server:
  port: 10011
spring:
  application:
#    name: xred-service-discovery-nacos-provider
    name: xred-service-discovery-multi-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
