server:
  port: 10022
spring:
  application:
    name: xred-service-discovery-multi-consumer
  autoconfigure:
    exclude: org.springframework.cloud.client.serviceregistry.ServiceRegistryAutoConfiguration,org.springframework.cloud.client.serviceregistry.AutoServiceRegistrationAutoConfiguration
  nacos:
    discovery:
      server-addr: localhost:8848
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        instance-id: ${spring.application.name}-01
        service-name: ${spring.application.name}
        port: ${server.port}
        prefer-ip-address: true
        ip-address: ${spring.cloud.client.ip-address}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10013/eureka