server:
  port: 10022
spring:
  application:
    name: xred-service-discovery-multi-consumer
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10013/eureka