server:
  port: 10061
spring:
  application:
    name: xred-service-config-scc-client
  config:
    import: optional:configserver:${spring.cloud.config.uri}
  cloud:
    config:
#      discovery:
#        enabled: true
#        service-id: xred-service-config-scc-server
      name: ${spring.application.name}
      profile: test
      uri: http://localhost:10060/
      label: main
  profiles:
    active: test
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

custom:
  user:
    id: NativeID
    name: NativeName
