server:
  port: 10041
spring:
  application:
    name: xred-service-monitor-actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
