server:
  port: 10013
spring:
  application:
    name: xred-service-discovery-eureka-server
eureka:
  client:
    register-with-eureka: false # ????????????????????????
    fetch-registry: false # ?? Eureka Server ???????
