server:
  port: 10019
spring:
  application:
#    name: xred-service-discovery-consul-provider
    name: xred-service-discovery-multi-provider
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        instance-id: ${spring.application.name}-01
        service-name: ${spring.application.name}
        port: ${server.port}
        prefer-ip-address: true
        ip-address: ${spring.cloud.client.ip-address}