### ECHO TEST
GET http://localhost:10012/hello

### 获取Services列表
GET http://localhost:10012/info

###
GET http://localhost:10015/info

###
GET http://localhost:10015/hello

###
GET http://localhost:10016/info

###
GET http://localhost:10016/hello

###
GET http://localhost:10018/hello

###
GET http://localhost:10022/info

###
GET http://localhost:10022/hello
