server:
  port: 10061
spring:
  application:
    name: xred-service-config-scc
  profiles:
    active: prod
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

